use_frameworks!

platform :ios, '9.0'

target 'AXViewControllerTransitioning_Example' do
  pod 'AXViewControllerTransitioning', :path => '../'

  target 'AXViewControllerTransitioning_Tests' do
    inherit! :search_paths

    
  end
end
