use_frameworks!
inhibit_all_warnings!
platform :ios, '9.0'

target 'AXViewControllerTransitioning_Example' do
  pod 'AXViewControllerTransitioning', :path => '../'
  pod 'Masonry'
  target 'AXViewControllerTransitioning_Tests' do
    inherit! :search_paths

    
  end
end
#=========忽略===========
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
    end
  end
end
